### ISSUE TITLE
Stopped working with 4.9700

### ISSUE THREAD

**Issue by m0rph13** [moroen/IKEA-Tradfri-plugin#39]
Hi.
With the new Domoticz version (4.9700) , all my Trådfri devices disapeared from presentation. I can still see them under devices.

In the logs, I see:

`2018-07-01 01:02:01.548 Error: (IKEA Tradfri) 'onMessage' failed 'TypeError':'onMessage() missing 2 required positional arguments: 'Status' and 'Extra''.`

**Comment by m0rph13** [comment]
Tried switching to the development-branch and restarted with
`sudo systemctl restart ikea-tradfri.service`
In the logs I saw that a new connection was made and then the same error again.

**Comment by m0rph13** [comment]
That particlar problem went away with a total restart of the system.
However, none of my IKEA Trådfri switches are shown, but they work fine when activating/deactivating from the Settings -> Devices listing..

**Comment by moroen** [comment]
The latest commit to the master branch is for the latest stable, you should switch back to master and restart both domoticz and ikea-tradfri.service. Note: the order is important, you need to stop domoticz first, then the ikea-tradfri.service, checkout the master branch and pull changes, then restart ikea-tradfri.service and finally domoticz...
